//! `postgresql.conf` and `postgresql.auto.conf`: the reader of `guc-file.l`, the rules of
//! `ProcessConfigFileInternal` in `guc.c` for the start and for a reload, and the file that
//! `initdb` writes.
//!
//! The server keeps one set of values, as the postmaster of PostgreSQL does: the command line
//! first, then the files. A reload reads the files again, logs each change with the text of
//! PostgreSQL, and gives the sessions the new values. A session takes them before the next
//! message that it handles, as a backend does after `SIGHUP`.

use std::collections::HashSet;
use std::path::Path;

use rudb_common::error::Error;
use rudb_common::guc::{Context, Settings, find, valid_custom_name};

use crate::hba;
use crate::tls::os_text;

/// The file that `ALTER SYSTEM` writes, in the data directory.
pub(crate) const AUTO_FILE: &str = "postgresql.auto.conf";

/// `CONF_FILE_MAX_DEPTH`: the deepest level of `include` files.
const MAX_DEPTH: u32 = 10;

/// The number of syntax errors in one file after which the reader stops.
const MAX_SYNTAX_ERRORS: u32 = 100;

/// The text of a file with `@` names that `init` writes as `postgresql.conf`.
const SAMPLE: &str = include_str!("../vendor/postgresql.conf.sample");

/// The text of `postgresql.auto.conf` after `initdb`.
pub(crate) const AUTO_TEXT: &str =
    "# Do not edit this file manually!\n# It will be overwritten by the ALTER SYSTEM command.\n";

/// One `name = value` line of a file, `ConfigVariable` in `guc.h`.
#[derive(Debug, Clone)]
struct Item {
    name: String,
    value: String,
    file: String,
    line: u32,
    ignore: bool,
}

/// The tokens of `guc-file.l`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Token {
    Eof,
    Eol,
    Id,
    QualifiedId,
    String,
    Unquoted,
    Integer,
    Real,
    Equals,
    Error,
}

/// The scanner of `guc-file.l`. A token is the longest match of the rules, and of two matches of
/// one length the first rule wins, as in `flex`.
struct Lexer<'a> {
    text: &'a [u8],
    at: usize,
    start: usize,
    /// `ConfigFileLineno`, one more after each end of line.
    line: u32,
}

fn letter(c: u8) -> bool {
    c.is_ascii_alphabetic() || c == b'_' || c >= 0x80
}

fn letter_or_digit(c: u8) -> bool {
    letter(c) || c.is_ascii_digit()
}

/// The length of the run of bytes at the start of `text` that `class` takes.
fn run(text: &[u8], class: impl Fn(u8) -> bool) -> usize {
    text.iter().take_while(|&&c| class(c)).count()
}

impl<'a> Lexer<'a> {
    fn new(text: &'a [u8]) -> Lexer<'a> {
        Lexer { text, at: 0, start: 0, line: 1 }
    }

    /// The text of the last token.
    fn token(&self) -> String {
        String::from_utf8_lossy(&self.text[self.start..self.at]).into_owned()
    }

    fn next(&mut self) -> Token {
        loop {
            let rest = &self.text[self.at..];
            let Some(&first) = rest.first() else {
                self.start = self.at;
                return Token::Eof;
            };
            self.start = self.at;
            match first {
                b'\n' => {
                    self.at += 1;
                    self.line += 1;
                    return Token::Eol;
                }
                b' ' | b'\t' | b'\r' => {
                    self.at += run(rest, |c| matches!(c, b' ' | b'\t' | b'\r'));
                    continue;
                }
                b'#' => {
                    self.at += run(rest, |c| c != b'\n');
                    continue;
                }
                _ => {}
            }
            let id = if letter(first) { 1 + run(&rest[1..], letter_or_digit) } else { 0 };
            let qualified = if id > 0
                && rest.get(id) == Some(&b'.')
                && rest.get(id + 1).is_some_and(|&c| letter(c))
            {
                id + 2 + run(&rest[id + 2..], letter_or_digit)
            } else {
                0
            };
            let unquoted = if letter(first) {
                1 + run(&rest[1..], |c| {
                    letter_or_digit(c) || matches!(c, b'-' | b'.' | b'_' | b':' | b'/')
                })
            } else {
                0
            };
            let candidates = [
                (id, Token::Id),
                (qualified, Token::QualifiedId),
                (quoted(rest), Token::String),
                (unquoted, Token::Unquoted),
                (integer(rest), Token::Integer),
                (real(rest), Token::Real),
                (usize::from(first == b'='), Token::Equals),
                (1, Token::Error),
            ];
            let mut best = (0, Token::Error);
            for (len, token) in candidates {
                if len > best.0 {
                    best = (len, token);
                }
            }
            self.at += best.0;
            return best.1;
        }
    }
}

/// The length of `STRING` at the start of `text`: `'([^'\\\n]|\\.|'')*'`, 0 for no match.
fn quoted(text: &[u8]) -> usize {
    if text.first() != Some(&b'\'') {
        return 0;
    }
    let mut longest = 0;
    let mut at = 1;
    while let Some(&c) = text.get(at) {
        match c {
            b'\\' => match text.get(at + 1) {
                Some(&next) if next != b'\n' => at += 2,
                _ => break,
            },
            b'\n' => break,
            b'\'' => {
                longest = at + 1;
                if text.get(at + 1) != Some(&b'\'') {
                    break;
                }
                at += 2;
            }
            _ => at += 1,
        }
    }
    longest
}

/// The length of a sign at the start of `text`.
fn sign(text: &[u8]) -> usize {
    usize::from(matches!(text.first(), Some(b'-' | b'+')))
}

/// The length of `INTEGER`: `{SIGN}?({DIGIT}+|0x{HEXDIGIT}+){UNIT_LETTER}*`.
fn integer(text: &[u8]) -> usize {
    let at = sign(text);
    let rest = &text[at..];
    let mut longest = 0;
    let digits = run(rest, |c| c.is_ascii_digit());
    if digits > 0 {
        longest = at + digits + run(&rest[digits..], |c| c.is_ascii_alphabetic());
    }
    if rest.starts_with(b"0x") {
        let hex = run(&rest[2..], |c| c.is_ascii_hexdigit());
        if hex > 0 {
            let len = 2 + hex;
            longest = longest.max(at + len + run(&rest[len..], |c| c.is_ascii_alphabetic()));
        }
    }
    longest
}

/// The length of `REAL`: `{SIGN}?{DIGIT}*"."{DIGIT}*{EXPONENT}?`.
fn real(text: &[u8]) -> usize {
    let mut at = sign(text);
    at += run(&text[at..], |c| c.is_ascii_digit());
    if text.get(at) != Some(&b'.') {
        return 0;
    }
    at += 1;
    at += run(&text[at..], |c| c.is_ascii_digit());
    if matches!(text.get(at), Some(b'e' | b'E')) {
        let mut end = at + 1;
        end += sign(&text[end..]);
        let digits = run(&text[end..], |c| c.is_ascii_digit());
        if digits > 0 {
            at = end + digits;
        }
    }
    at
}

/// `DeescapeQuotedString`: the value of a quoted string, without the quotes. The value ends at a
/// zero byte, as a C string does.
fn deescape(token: &[u8]) -> String {
    let body = &token[1..token.len() - 1];
    let mut out = Vec::with_capacity(body.len());
    let mut at = 0;
    while at < body.len() {
        let c = body[at];
        if c == b'\\' && at + 1 < body.len() {
            at += 1;
            let escaped = body[at];
            out.push(match escaped {
                b'b' => 0x08,
                b'f' => 0x0c,
                b'n' => b'\n',
                b'r' => b'\r',
                b't' => b'\t',
                b'0'..=b'7' => {
                    let digits = run(&body[at..], |c| (b'0'..=b'7').contains(&c)).min(3);
                    let value = body[at..at + digits]
                        .iter()
                        .fold(0u32, |value, &d| (value << 3) + u32::from(d - b'0'));
                    at += digits - 1;
                    value as u8
                }
                other => other,
            });
        } else if c == b'\'' && body.get(at + 1) == Some(&b'\'') {
            out.push(b'\'');
            at += 1;
        } else {
            out.push(c);
        }
        at += 1;
    }
    if let Some(end) = out.iter().position(|&c| c == 0) {
        out.truncate(end);
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// The reader of the files, `ParseConfigFile`, `ParseConfigFp` and `ParseConfigDirectory`. It
/// keeps the items in the order of the files and writes each error to `log`.
struct Reader<'a> {
    /// The data directory, absolute, for a file name without a calling file.
    data: &'a str,
    items: Vec<Item>,
    log: &'a mut Vec<String>,
}

impl Reader<'_> {
    /// `ParseConfigFile`. `strict` is false for `include_if_exists` and `postgresql.auto.conf`,
    /// which can be missing.
    fn file(&mut self, name: &str, strict: bool, calling: Option<&str>, depth: u32) -> bool {
        if name.trim_matches([' ', '\t', '\r', '\n']).is_empty() {
            self.log.push(format!("empty configuration file name: \"{name}\""));
            return false;
        }
        if depth > MAX_DEPTH {
            self.log.push(format!(
                "could not open configuration file \"{name}\": maximum nesting depth exceeded"
            ));
            return false;
        }
        let path = match calling {
            _ if Path::new(name).is_absolute() => name.to_owned(),
            Some(calling) => hba::absolute_location(name, Some(calling)),
            None => hba::canonical(&Path::new(self.data).join(name)),
        };
        if let Some(calling) = calling
            && path == calling
        {
            self.log.push(format!("configuration file recursion in \"{calling}\""));
            return false;
        }
        match std::fs::read(&path) {
            Ok(text) => self.text(&text, &path, depth),
            Err(e) if strict => {
                self.log
                    .push(format!("could not open configuration file \"{path}\": {}", os_text(&e)));
                false
            }
            Err(_) => {
                self.log.push(format!("skipping missing configuration file \"{path}\""));
                true
            }
        }
    }

    /// `ParseConfigDirectory`: each file of `include_dir` in the order of the names.
    fn directory(&mut self, name: &str, calling: &str, depth: u32) -> bool {
        match hba::conf_files(calling, name) {
            Ok(files) => files.iter().all(|file| self.file(file, true, Some(calling), depth)),
            Err((text, _)) => {
                self.log.push(text);
                false
            }
        }
    }

    /// `ParseConfigFp`: the lines of one file. After a syntax error the reader goes on at the
    /// next line, so that one read reports all the errors of a file.
    fn text(&mut self, text: &[u8], file: &str, depth: u32) -> bool {
        let mut lexer = Lexer::new(text);
        let mut ok = true;
        let mut errors = 0;
        loop {
            let mut token = lexer.next();
            match token {
                Token::Eof => break,
                Token::Eol => continue,
                _ => {}
            }
            let failed = 'line: {
                if token != Token::Id && token != Token::QualifiedId {
                    break 'line true;
                }
                let name = lexer.token();
                token = lexer.next();
                if token == Token::Equals {
                    token = lexer.next();
                }
                let value = match token {
                    Token::String => deescape(&text[lexer.start..lexer.at]),
                    Token::Id | Token::Integer | Token::Real | Token::Unquoted => lexer.token(),
                    _ => break 'line true,
                };
                token = lexer.next();
                if token != Token::Eol {
                    if token != Token::Eof {
                        break 'line true;
                    }
                    lexer.line += 1;
                }
                let line = lexer.line - 1;
                let included = match name.to_ascii_lowercase().as_str() {
                    "include_dir" => Some(self.directory(&value, file, depth + 1)),
                    "include_if_exists" => Some(self.file(&value, false, Some(file), depth + 1)),
                    "include" => Some(self.file(&value, true, Some(file), depth + 1)),
                    _ => None,
                };
                match included {
                    Some(done) => ok &= done,
                    None => self.items.push(Item {
                        name,
                        value,
                        file: file.to_owned(),
                        line,
                        ignore: false,
                    }),
                }
                false
            };
            if !failed {
                if token == Token::Eof {
                    break;
                }
                continue;
            }
            if matches!(token, Token::Eol | Token::Eof) {
                self.log.push(format!(
                    "syntax error in file \"{file}\" line {}, near end of line",
                    lexer.line - 1
                ));
            } else {
                self.log.push(format!(
                    "syntax error in file \"{file}\" line {}, near token \"{}\"",
                    lexer.line,
                    lexer.token()
                ));
            }
            ok = false;
            errors += 1;
            if errors >= MAX_SYNTAX_ERRORS {
                self.log.push(format!("too many syntax errors found, abandoning file \"{file}\""));
                break;
            }
            while !matches!(token, Token::Eol | Token::Eof) {
                token = lexer.next();
            }
            if token == Token::Eof {
                break;
            }
        }
        ok
    }
}

/// The text of an error for the log, with its `DETAIL` and `HINT` lines.
pub(crate) fn error_text(error: &Error) -> String {
    let mut text = error.message().to_owned();
    if let Some(fields) = error.fields() {
        if let Some(detail) = &fields.detail {
            text.push_str("\nDETAIL:  ");
            text.push_str(detail);
        }
        if let Some(hint) = &fields.hint {
            text.push_str("\nHINT:  ");
            text.push_str(hint);
        }
    }
    text
}

/// The key of a name: the name of the parameter in lower case, or the name of a placeholder in
/// lower case.
fn key(name: &str) -> String {
    find(name).map_or(name, |parameter| parameter.name).to_ascii_lowercase()
}

/// The values of the server, with the rules of the postmaster of PostgreSQL.
#[derive(Debug)]
pub(crate) struct State {
    settings: Settings,
    /// The data directory, absolute.
    data: String,
    /// `config_file`, absolute.
    file: String,
    /// The items of the files that the server took at the last read that applied changes, in
    /// the order of the files. A session takes the same items.
    applied: Vec<(String, String)>,
}

/// What `set_config_option` gives: the value changed, the value did not change, or an error.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Set {
    Changed,
    Kept,
    Failed,
}

impl State {
    /// The values of the command line, for the data directory `data`.
    pub(crate) fn new(data: &Path, args: &[(String, String)]) -> State {
        let data = match std::env::current_dir() {
            Ok(dir) if data.is_relative() => hba::canonical(&dir.join(data)),
            _ => hba::canonical(data),
        };
        let file = format!("{data}/postgresql.conf");
        let mut settings = Settings::new(true);
        for (name, value) in args {
            // The command line was checked before. A name of the server alone is not here.
            let _ = settings.set_argument(name, value);
        }
        State { settings, data, file, applied: Vec::new() }
    }

    /// The absolute path of `postgresql.conf`.
    pub(crate) fn config_file(&self) -> &str {
        &self.file
    }

    /// The absolute path of the data directory.
    pub(crate) fn data(&self) -> &str {
        &self.data
    }

    /// The items that the sessions take, in order.
    pub(crate) fn applied(&self) -> &[(String, String)] {
        &self.applied
    }

    /// The value of a parameter that the files set, as `SHOW` gives it, or `None` when the value
    /// did not come from the files.
    pub(crate) fn file_value(&self, name: &str) -> Option<String> {
        let key = key(name);
        self.settings
            .file_names()
            .iter()
            .any(|held| held.eq_ignore_ascii_case(&key))
            .then(|| self.settings.get(name))
            .flatten()
    }

    /// The two reads of `SelectConfigFiles` at start: `postgresql.conf` alone, and then both
    /// files with the checks and the values.
    ///
    /// # Errors
    ///
    /// The text of the `FATAL` error of PostgreSQL for a file that is not there or that has an
    /// error. The details of each error are in `log`.
    pub(crate) fn start(&mut self, log: &mut Vec<String>) -> Result<(), String> {
        if let Err(e) = std::fs::metadata(&self.file) {
            return Err(format!(
                "could not access the server configuration file \"{}\": {}",
                self.file,
                os_text(&e)
            ));
        }
        let mut reader = Reader { data: &self.data, items: Vec::new(), log: &mut *log };
        if !reader.file(&self.file, true, None, 0) {
            return Err(format!("configuration file \"{}\" contains errors", self.file));
        }
        self.process(false, log)
    }

    /// The read after `SIGHUP`. Each change and each error goes to `log`.
    pub(crate) fn reload(&mut self, log: &mut Vec<String>) {
        let _ = self.process(true, log);
    }

    /// `ProcessConfigFileInternal`.
    fn process(&mut self, reload: bool, log: &mut Vec<String>) -> Result<(), String> {
        let mut with_error = self.file.clone();
        let mut error = false;
        let mut applying = false;
        'bail: {
            let mut reader = Reader { data: &self.data, items: Vec::new(), log: &mut *log };
            if !reader.file(&self.file.clone(), true, None, 0) {
                error = true;
                break 'bail;
            }
            if !reader.file(AUTO_FILE, false, None, 0) {
                error = true;
                with_error = AUTO_FILE.to_owned();
                break 'bail;
            }
            let mut items = reader.items;
            let mut in_file = HashSet::new();
            for at in 0..items.len() {
                if items[at].ignore {
                    continue;
                }
                let name = items[at].name.clone();
                if self.settings.get(&name).is_some() {
                    if !in_file.insert(key(&name)) {
                        for earlier in &mut items[..at] {
                            if earlier.name == name {
                                earlier.ignore = true;
                            }
                        }
                    }
                } else if !valid_custom_name(&name) {
                    log.push(format!(
                        "unrecognized configuration parameter \"{name}\" in file \"{}\" line {}",
                        items[at].file, items[at].line
                    ));
                    error = true;
                    with_error = items[at].file.clone();
                }
            }
            if error {
                break 'bail;
            }
            applying = true;
            for name in self.settings.file_names() {
                if in_file.contains(&key(&name)) {
                    continue;
                }
                if find(&name)
                    .is_some_and(|p| matches!(p.context, Context::Internal | Context::Postmaster))
                {
                    log.push(format!(
                        "parameter \"{name}\" cannot be changed without restarting the server"
                    ));
                    error = true;
                    continue;
                }
                if self.settings.set_file(&name, None).unwrap_or(false) && reload {
                    log.push(format!(
                        "parameter \"{name}\" removed from configuration file, reset to default"
                    ));
                }
            }
            let mut applied = Vec::new();
            for item in items.iter().filter(|item| !item.ignore) {
                let before = reload.then(|| self.settings.get(&item.name).unwrap_or_default());
                match self.set(item, reload, log) {
                    Set::Failed => {
                        error = true;
                        with_error = item.file.clone();
                        continue;
                    }
                    Set::Changed => {
                        if let Some(before) = before
                            && before != self.settings.get(&item.name).unwrap_or_default()
                        {
                            log.push(format!(
                                "parameter \"{}\" changed to \"{}\"",
                                item.name, item.value
                            ));
                        }
                    }
                    Set::Kept => {}
                }
                applied.push((item.name.clone(), item.value.clone()));
            }
            self.applied = applied;
        }
        if !error {
            return Ok(());
        }
        if !reload {
            return Err(format!("configuration file \"{with_error}\" contains errors"));
        }
        let what =
            if applying { "unaffected changes were applied" } else { "no changes were applied" };
        log.push(format!("configuration file \"{with_error}\" contains errors; {what}"));
        Ok(())
    }

    /// `set_config_option` with the source `PGC_S_FILE`, in the postmaster.
    fn set(&mut self, item: &Item, reload: bool, log: &mut Vec<String>) -> Set {
        if let Some(parameter) = find(&item.name) {
            match parameter.context {
                Context::Internal => {
                    log.push(format!("parameter \"{}\" cannot be changed", parameter.name));
                    return Set::Failed;
                }
                Context::Postmaster if reload => {
                    return match self.settings.check(parameter, &item.value) {
                        Err(e) => {
                            log.push(error_text(&e));
                            Set::Failed
                        }
                        Ok(value) if value != self.settings.setting(parameter) => {
                            log.push(format!(
                                "parameter \"{}\" cannot be changed without restarting the server",
                                parameter.name
                            ));
                            Set::Failed
                        }
                        Ok(_) => Set::Kept,
                    };
                }
                _ => {}
            }
        }
        match self.settings.set_file(&item.name, Some(&item.value)) {
            Ok(true) => Set::Changed,
            Ok(false) => Set::Kept,
            Err(e) => {
                log.push(error_text(&e));
                Set::Failed
            }
        }
    }
}

/// Whether a session takes a new value of a parameter at a reload. A backend keeps the values
/// that only the start of the server or of the session can set.
fn reloadable(name: &str) -> bool {
    find(name).is_none_or(|parameter| {
        !matches!(
            parameter.context,
            Context::Internal | Context::Postmaster | Context::Backend | Context::SuperuserBackend
        )
    })
}

/// The values of the files for a new session. A value that the session cannot take is left out,
/// as a backend logs such an error only at `DEBUG` levels.
pub(crate) fn start_session(settings: &mut Settings, file: &[(String, String)]) {
    for (name, value) in file {
        let _ = settings.set_file(name, Some(value));
    }
}

/// The change of the values of the files in a session after a reload: the parameters that left
/// the files go back to their defaults, and the others take their new values.
pub(crate) fn reload_session(
    settings: &mut Settings,
    old: &[(String, String)],
    new: &[(String, String)],
) {
    let kept: HashSet<String> = new.iter().map(|(name, _)| key(name)).collect();
    let mut removed = HashSet::new();
    for (name, _) in old {
        if reloadable(name) && !kept.contains(&key(name)) && removed.insert(key(name)) {
            let _ = settings.set_file(name, None);
        }
    }
    for (name, value) in new {
        if reloadable(name) {
            let _ = settings.set_file(name, Some(value));
        }
    }
}

/// `guc_value_requires_quotes` of `initdb`: a value other than a name or a number with a unit
/// needs quotes.
fn requires_quotes(value: &str) -> bool {
    let bytes = value.as_bytes();
    match bytes.first() {
        None => true,
        Some(c) if c.is_ascii_alphabetic() => !bytes.iter().all(u8::is_ascii_alphanumeric),
        Some(c) if c.is_ascii_digit() => {
            let digits = run(bytes, |c| c.is_ascii_digit());
            !bytes[digits..].iter().all(u8::is_ascii_alphabetic)
        }
        Some(_) => true,
    }
}

/// `replace_guc_value` of `initdb`: the line that sets `name`, with or without the `#` in front of
/// it, gets the new value and keeps its comment at the same column. A file with no such line
/// gets a new line at its end.
fn replace_value(lines: &mut Vec<String>, name: &str, value: &str, comment: bool) {
    let mut line = String::from(if comment { "#" } else { "" });
    line.push_str(name);
    line.push_str(" = ");
    if requires_quotes(value) {
        line.push('\'');
        line.push_str(&value.replace('\'', "''").replace('\\', "\\\\"));
        line.push('\'');
    } else {
        line.push_str(value);
    }
    for old in lines.iter_mut() {
        let bytes = old.as_bytes();
        let start = run(bytes, |c| c == b'#' || c.is_ascii_whitespace());
        let Some(found) = old.get(start..start + name.len()) else { continue };
        if !found.eq_ignore_ascii_case(name) {
            continue;
        }
        let after =
            start + name.len() + run(&bytes[start + name.len()..], |c| c.is_ascii_whitespace());
        if bytes.get(after) != Some(&b'=') {
            continue;
        }
        let at = usize::from(comment);
        line.replace_range(at..at + name.len(), found);
        match old[after..].rfind('#') {
            Some(hash) => {
                let hash = after + hash;
                let indent = hash.max(line.len() + 1);
                while line.len() < indent {
                    line.push(' ');
                }
                line.push_str(&old[hash..]);
            }
            None => line.push('\n'),
        }
        *old = line;
        return;
    }
    line.push('\n');
    lines.push(line);
}

/// The `postgresql.conf` that `initdb` writes with `--locale=C`, the time zone `UTC` and the
/// methods `local` and `host` of `pg_hba.conf`.
pub(crate) fn sample(local: &str, host: &str) -> String {
    let mut lines: Vec<String> = SAMPLE.split_inclusive('\n').map(str::to_owned).collect();
    let boot = |name: &str| {
        find(name).map(|parameter| parameter.show(&parameter.boot())).unwrap_or_default()
    };
    for (name, value) in [
        ("max_connections", "100"),
        ("autovacuum_worker_slots", "16"),
        ("shared_buffers", "128MB"),
        ("lc_messages", "C"),
        ("lc_monetary", "C"),
        ("lc_numeric", "C"),
        ("lc_time", "C"),
        ("datestyle", "iso, mdy"),
        ("default_text_search_config", "pg_catalog.english"),
        ("timezone", "UTC"),
        ("log_timezone", "UTC"),
        ("dynamic_shared_memory_type", "posix"),
        ("min_wal_size", "80MB"),
        ("max_wal_size", "1GB"),
    ] {
        replace_value(&mut lines, name, value, false);
    }
    replace_value(&mut lines, "unix_socket_directories", "/tmp", true);
    replace_value(&mut lines, "port", "5432", true);
    // The flush defaults depend on the platform, and `initdb` writes the ones that are not 0.
    for name in ["backend_flush_after", "bgwriter_flush_after", "checkpoint_flush_after"] {
        let value = boot(name);
        if value != "0" && !value.is_empty() {
            replace_value(&mut lines, name, &value, true);
        }
    }
    if (local == "md5" && host != "scram-sha-256") || (host == "md5" && local != "scram-sha-256") {
        replace_value(&mut lines, "password_encryption", "md5", false);
    }
    if boot("default_toast_compression") == "lz4" {
        replace_value(&mut lines, "default_toast_compression", "lz4", true);
    }
    lines.concat()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tokens(text: &str) -> Vec<(Token, String)> {
        let mut lexer = Lexer::new(text.as_bytes());
        let mut out = Vec::new();
        loop {
            let token = lexer.next();
            if token == Token::Eof {
                return out;
            }
            out.push((token, lexer.token()));
        }
    }

    #[test]
    fn the_tokens_of_guc_file_l() {
        use Token::*;
        let found = tokens("a.b = 'x''y' # c\nwork_mem 4MB\na.b.c = -1.5e3 0x1Fkb . =\n'open");
        let expected = [
            (QualifiedId, "a.b"),
            (Equals, "="),
            (String, "'x''y'"),
            (Eol, "\n"),
            (Id, "work_mem"),
            (Integer, "4MB"),
            (Eol, "\n"),
            (Unquoted, "a.b.c"),
            (Equals, "="),
            (Real, "-1.5e3"),
            (Integer, "0x1Fkb"),
            (Real, "."),
            (Equals, "="),
            (Eol, "\n"),
            (Error, "'"),
            (Id, "open"),
        ];
        let expected: Vec<(Token, std::string::String)> =
            expected.iter().map(|(t, s)| (*t, (*s).to_owned())).collect();
        assert_eq!(found, expected);
        assert_eq!(tokens("1e5")[0], (Integer, "1e".to_owned()));
        assert_eq!(tokens("/tmp")[0], (Error, "/".to_owned()));
    }

    #[test]
    fn quoted_strings_lose_their_escapes() {
        assert_eq!(deescape(br"'a\tb\'c''d\101\0x'"), "a\tb'c'dA");
        assert_eq!(deescape(b"''"), "");
    }

    fn read(text: &str) -> (Vec<(String, String, u32)>, Vec<String>, bool) {
        let mut log = Vec::new();
        let mut reader = Reader { data: "/d", items: Vec::new(), log: &mut log };
        let ok = reader.text(text.as_bytes(), "/d/postgresql.conf", 0);
        let items = reader.items.into_iter().map(|i| (i.name, i.value, i.line)).collect();
        (items, log, ok)
    }

    #[test]
    fn syntax_errors_name_the_line_and_the_reader_goes_on() {
        let (items, log, ok) = read("a = \nwork_mem = 1 2\n\nport = 5433\nb =");
        assert!(!ok);
        assert_eq!(items, [("port".to_owned(), "5433".to_owned(), 4)]);
        assert_eq!(
            log,
            [
                "syntax error in file \"/d/postgresql.conf\" line 1, near end of line",
                "syntax error in file \"/d/postgresql.conf\" line 2, near token \"2\"",
                "syntax error in file \"/d/postgresql.conf\" line 4, near end of line",
            ]
        );
        let (items, _, ok) = read("x.y 'v'");
        assert!(ok);
        assert_eq!(items, [("x.y".to_owned(), "v".to_owned(), 1)]);
    }

    #[test]
    fn initdb_quotes_and_keeps_the_comment_column() {
        let mut lines = vec![
            "#timezone = 'GMT'\n".to_owned(),
            "#port = 1234          # (change requires restart)\n".to_owned(),
        ];
        replace_value(&mut lines, "timezone", "Etc/UTC", false);
        replace_value(&mut lines, "port", "5432", true);
        replace_value(&mut lines, "lc_time", "C", false);
        assert_eq!(lines[0], "timezone = 'Etc/UTC'\n");
        assert_eq!(lines[1], "#port = 5432          # (change requires restart)\n");
        assert_eq!(lines[2], "lc_time = C\n");
        assert!(!requires_quotes("128MB"));
        assert!(requires_quotes("iso, mdy"));
        assert!(requires_quotes(""));
    }
}
