//! The Unicode normalization tables of PostgreSQL, from `unicode_norm_table.h`.
//!
//! The header has `UnicodeDecompMain`, with the combining class and the decomposition of each code
//! point that has one of them, and `UnicodeDecomp_codepoints`, the code points of the
//! decompositions that are not inline. The backend finds the pair that composes into a code point
//! with a perfect hash. Here the generator writes the same pairs as a sorted table, from the entries
//! that decompose into two code points and that are not marked as not for composition, which is
//! the loop of the frontend in `unicode_norm.c`.

use std::fmt::Write as _;

/// One entry of `UnicodeDecompMain`.
struct Entry {
    codepoint: u32,
    class: u8,
    flags: u8,
    index: u32,
}

/// The values of the flags of `dec_size_flags`.
const FLAGS: [(&str, u8); 3] =
    [("DECOMP_NO_COMPOSE", 0x80), ("DECOMP_INLINE", 0x40), ("DECOMP_COMPAT", 0x20)];

/// Renders the tables of `rudb_kernels::pgnormalize` from the text of `unicode_norm_table.h`.
pub(super) fn tables(texts: &[String]) -> Result<String, String> {
    let text = &texts[0];
    for (name, value) in FLAGS {
        let defined = text.lines().find_map(|line| {
            let mut words = line.split_whitespace();
            (words.next() == Some("#define") && words.next() == Some(name)).then(|| words.next())
        });
        let want = format!("0x{value:02X}");
        if defined != Some(Some(want.as_str())) {
            return Err(format!("unicode_norm_table.h: {name} is not 0x{value:02X}"));
        }
    }
    let entries = entries(array(text, "UnicodeDecompMain")?)?;
    let codepoints = codepoints(array(text, "UnicodeDecomp_codepoints")?)?;
    if entries.windows(2).any(|pair| pair[0].codepoint >= pair[1].codepoint) {
        return Err("unicode_norm_table.h: UnicodeDecompMain is not sorted".to_string());
    }
    let mut pairs = Vec::new();
    for entry in &entries {
        let size = entry.flags & 0x1F;
        let inline = entry.flags & 0x40 != 0;
        let end = entry.index as usize + usize::from(size);
        if inline && size != 1
            || inline && entry.index > 0xFFFF
            || !inline && end > codepoints.len()
        {
            return Err(format!(
                "unicode_norm_table.h: a bad decomposition of {:X}",
                entry.codepoint
            ));
        }
        if size == 2 && entry.flags & 0xA0 == 0 {
            let at = entry.index as usize;
            pairs.push((codepoints[at], codepoints[at + 1], entry.codepoint));
        }
    }
    pairs.sort_unstable();
    if pairs.windows(2).any(|pair| (pair[0].0, pair[0].1) == (pair[1].0, pair[1].1)) {
        return Err("unicode_norm_table.h: two code points compose from one pair".to_string());
    }

    let mut out = String::from(
        "//! The Unicode normalization tables of PostgreSQL.\n\
         //!\n\
         //! @generated by `cargo xtask pg-vendor` from `crates/rudb-kernels/vendor/unicode_norm_table.h`.\n\
         //! Do not edit. `cargo xtask pg-check` runs in the gate and fails if this file and the\n\
         //! vendored file disagree.\n\
         //!\n\
         //! `DECOMPOSITIONS` is `UnicodeDecompMain`: the code point, the combining class, the size\n\
         //! and the flags of the decomposition, and its index in `CODEPOINTS`, or the decomposition\n\
         //! itself when it is inline. `COMPOSITIONS` is each pair that composes into a code point,\n\
         //! sorted by the pair.\n\
         \n",
    );
    // The kernel reads the inline and the compatibility flags. The composition table holds the
    // flag of no composition.
    for (name, value) in &FLAGS[1..] {
        let _ = writeln!(out, "pub(super) const {name}: u8 = 0x{value:02X};");
    }
    let _ = writeln!(
        out,
        "\n#[rustfmt::skip]\npub(super) static DECOMPOSITIONS: [(u32, u8, u8, u16); {}] = [",
        entries.len()
    );
    rows(
        &mut out,
        entries.iter().map(|e| {
            format!("(0x{:05X}, {}, 0x{:02X}, {}),", e.codepoint, e.class, e.flags, e.index)
        }),
    );
    let _ = writeln!(
        out,
        "];\n\n#[rustfmt::skip]\npub(super) static CODEPOINTS: [u32; {}] = [",
        codepoints.len()
    );
    rows(&mut out, codepoints.iter().map(|c| format!("0x{c:05X},")));
    let _ = writeln!(
        out,
        "];\n\n#[rustfmt::skip]\npub(super) static COMPOSITIONS: [(u32, u32, u32); {}] = [",
        pairs.len()
    );
    rows(&mut out, pairs.iter().map(|(a, b, c)| format!("(0x{a:05X}, 0x{b:05X}, 0x{c:05X}),")));
    out.push_str("];\n");
    Ok(out)
}

/// The text between the braces of the array `name`.
fn array<'a>(text: &'a str, name: &str) -> Result<&'a str, String> {
    let missing = || format!("unicode_norm_table.h: no array {name}");
    let start = text.find(&format!(" {name}[")).ok_or_else(missing)?;
    let open = start + text[start..].find('{').ok_or_else(missing)?;
    let close = open + text[open..].find("};").ok_or_else(missing)?;
    Ok(&text[open + 1..close])
}

pub(super) fn number(text: &str) -> Result<u32, String> {
    let text = text.trim();
    let parsed = match text.strip_prefix("0x") {
        Some(hex) => u32::from_str_radix(hex, 16),
        None => text.parse(),
    };
    parsed.map_err(|_| format!("not a number: {text}"))
}

/// The entries of `UnicodeDecompMain`, one on each line as `{code, class, size | FLAGS, index}`.
fn entries(body: &str) -> Result<Vec<Entry>, String> {
    let mut entries = Vec::new();
    for line in body.lines().map(str::trim).filter(|line| !line.is_empty()) {
        let bad = || format!("unicode_norm_table.h: not an entry: {line}");
        let inner = line.strip_prefix('{').and_then(|l| l.split_once('}')).ok_or_else(bad)?.0;
        let fields: Vec<&str> = inner.split(", ").collect();
        let [codepoint, class, flags, index] = fields[..] else { return Err(bad()) };
        let mut parts = flags.split(" | ");
        let mut value = number(parts.next().ok_or_else(bad)?)?;
        for part in parts {
            let (_, flag) = FLAGS.iter().find(|(name, _)| *name == part).ok_or_else(bad)?;
            value |= u32::from(*flag);
        }
        entries.push(Entry {
            codepoint: number(codepoint)?,
            class: u8::try_from(number(class)?).map_err(|_| bad())?,
            flags: u8::try_from(value).map_err(|_| bad())?,
            index: number(index)?,
        });
    }
    Ok(entries)
}

/// The code points of `UnicodeDecomp_codepoints`, with the comment of each line left out.
fn codepoints(body: &str) -> Result<Vec<u32>, String> {
    let mut codepoints = Vec::new();
    for line in body.lines() {
        let line = match line.split_once("*/") {
            Some((_, rest)) => rest,
            None => line,
        };
        for item in line.split(',').map(str::trim).filter(|item| !item.is_empty()) {
            codepoints.push(number(item)?);
        }
    }
    Ok(codepoints)
}

/// The items, as many on a line as fit in 100 columns.
pub(super) fn rows(out: &mut String, items: impl Iterator<Item = String>) {
    let mut line = String::from("   ");
    for item in items {
        if line.len() + 1 + item.len() > 100 {
            out.push_str(&line);
            out.push('\n');
            line = String::from("   ");
        }
        line.push(' ');
        line.push_str(&item);
    }
    if line.len() > 3 {
        out.push_str(&line);
        out.push('\n');
    }
}
