//! The Unicode case and category tables of PostgreSQL, from `unicode_case_table.h`,
//! `unicode_category_table.h` and `unicode_category.h`.
//!
//! `unicode_case_table.h` has the four simple maps of case, `case_map_special` with the index of
//! the special mapping of each code point, and `case_map`, the index of each code point in the
//! maps. The backend finds the index with a search that the generator of PostgreSQL writes as C.
//! Here the generator reads the code point of each entry of `case_map` from its comment and
//! writes one sorted row for each code point that has an index, with its four mappings and its
//! special mapping. `unicode_category_table.h` has the general category of each range of code
//! points and the ranges of the properties, and `unicode_category.h` has the values of the
//! categories.

use std::fmt::Write as _;

use super::norm::{number, rows};

/// The case kinds in the order of `CaseKind`, which is the order of the maps in a row.
const KINDS: [&str; 4] = ["CaseLower", "CaseTitle", "CaseUpper", "CaseFold"];

/// The properties that the kernels read, by the name of their array and of their table here.
const PROPERTIES: [(&str, &str); 4] = [
    ("unicode_alphabetic", "ALPHABETIC"),
    ("unicode_lowercase", "LOWERCASE"),
    ("unicode_uppercase", "UPPERCASE"),
    ("unicode_case_ignorable", "CASE_IGNORABLE"),
];

/// Renders the tables of `rudb_kernels::pgunicode` from the text of `unicode_case_table.h`,
/// `unicode_category_table.h` and `unicode_category.h`.
pub(super) fn tables(texts: &[String]) -> Result<String, String> {
    let (cases, categories, names) = (&texts[0], &texts[1], &texts[2]);
    for (name, value) in [("MAX_CASE_EXPANSION", "3"), ("PG_U_FINAL_SIGMA", "(1 << 0)")] {
        let defined = cases.lines().find_map(|line| {
            let rest = line.strip_prefix("#define ")?.trim_start().strip_prefix(name)?;
            Some(rest.trim().to_string())
        });
        if defined.as_deref() != Some(value) {
            return Err(format!("unicode_case_table.h: {name} is not {value}"));
        }
    }
    for (at, kind) in KINDS.iter().enumerate() {
        if !cases.contains(&format!("{kind} = {at},")) {
            return Err(format!("unicode_case_table.h: {kind} is not {at}"));
        }
    }
    let index = entries("unicode_case_table.h", array(cases, "case_map")?)?;
    let maps = KINDS
        .iter()
        .map(|kind| {
            let name = format!("case_map_{}", kind["Case".len()..].to_lowercase());
            entries("unicode_case_table.h", array(cases, &name)?)
        })
        .collect::<Result<Vec<_>, _>>()?;
    let special = entries("unicode_case_table.h", array(cases, "case_map_special")?)?;
    let specials = specials(array(cases, "special_case")?)?;
    let size = maps[0].len();
    if maps.iter().any(|map| map.len() != size) || special.len() != size {
        return Err("unicode_case_table.h: the maps differ in size".to_string());
    }

    let mut rows_of_case = Vec::new();
    for &(at, codepoint) in &index {
        let at = at as usize;
        if at == 0 {
            continue;
        }
        if at >= size {
            return Err(format!("unicode_case_table.h: U+{codepoint:04X} has no entry"));
        }
        // Each entry of the maps names in its comment the first code point that has it, and
        // the partners in case, such as U+00C0 and U+00E0, share an entry.
        let named = maps[0][at].1;
        if maps.iter().chain([&special]).any(|map| map[at].1 != named)
            || index.iter().find(|entry| entry.0 as usize == at).map(|entry| entry.1) != Some(named)
        {
            return Err(format!("unicode_case_table.h: entry {at} is not U+{named:04X}"));
        }
        if special[at].0 as usize >= specials.len() {
            return Err(format!("unicode_case_table.h: a bad special case of U+{codepoint:04X}"));
        }
        rows_of_case.push((
            codepoint,
            [maps[0][at].0, maps[1][at].0, maps[2][at].0, maps[3][at].0],
            special[at].0,
        ));
    }
    rows_of_case.sort_unstable_by_key(|row| row.0);
    if rows_of_case.windows(2).any(|pair| pair[0].0 == pair[1].0) {
        return Err("unicode_case_table.h: a code point has two entries".to_string());
    }

    let variants = categories_of(names)?;
    let ranges_of_category = category_ranges(array(categories, "unicode_categories")?, &variants)?;

    let mut out = String::from(
        "//! The Unicode case and category tables of PostgreSQL.\n\
         //!\n\
         //! @generated by `cargo xtask pg-vendor` from `crates/rudb-kernels/vendor/unicode_case_table.h`,\n\
         //! `unicode_category_table.h` and `unicode_category.h`. Do not edit. `cargo xtask pg-check`\n\
         //! runs in the gate and fails if this file and the vendored files disagree.\n\
         //!\n\
         //! `CASES` has each code point that has a case mapping, sorted, with its lowercase,\n\
         //! titlecase, uppercase and case folded code point, and the index in `SPECIALS` of its\n\
         //! special mapping, or 0. A special mapping has its conditions and up to three code points\n\
         //! for each kind, in the same order. `CATEGORIES` has the general category of each range\n\
         //! of code points that has one, and the other tables are the ranges of a property.\n\
         \n",
    );
    let _ = writeln!(out, "/// The condition `Final_Sigma` of a special mapping.");
    let _ = writeln!(out, "pub(super) const FINAL_SIGMA: u8 = 1;\n");
    let _ =
        writeln!(out, "/// The general category of a code point, as `pg_unicode_category` has it.");
    let _ =
        writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub(super) enum Category {{");
    for (name, value) in &variants {
        let _ = writeln!(out, "    {name} = {value},");
    }
    let _ = writeln!(
        out,
        "}}\n\n#[rustfmt::skip]\npub(super) static CASES: [(u32, [u32; 4], u8); {}] = [",
        rows_of_case.len()
    );
    rows(
        &mut out,
        rows_of_case.iter().map(|(codepoint, map, special)| {
            format!(
                "(0x{codepoint:05X}, [0x{:05X}, 0x{:05X}, 0x{:05X}, 0x{:05X}], {special}),",
                map[0], map[1], map[2], map[3]
            )
        }),
    );
    let _ = writeln!(
        out,
        "];\n\n#[rustfmt::skip]\npub(super) static SPECIALS: [(u8, [[u32; 3]; 4]); {}] = [",
        specials.len()
    );
    rows(
        &mut out,
        specials.iter().map(|(conditions, map)| {
            let kinds: Vec<String> = map
                .iter()
                .map(|points| {
                    let points: Vec<String> = points.iter().map(|p| format!("0x{p:05X}")).collect();
                    format!("[{}]", points.join(", "))
                })
                .collect();
            format!("({conditions}, [{}]),", kinds.join(", "))
        }),
    );
    let _ = writeln!(
        out,
        "];\n\n#[rustfmt::skip]\npub(super) static CATEGORIES: [(u32, u32, Category); {}] = [",
        ranges_of_category.len()
    );
    rows(
        &mut out,
        ranges_of_category
            .iter()
            .map(|(first, last, name)| format!("(0x{first:05X}, 0x{last:05X}, Category::{name}),")),
    );
    out.push_str("];\n");
    for (array_name, name) in PROPERTIES {
        let ranges = ranges(array(categories, array_name)?)?;
        let _ = writeln!(
            out,
            "\n#[rustfmt::skip]\npub(super) static {name}: [(u32, u32); {}] = [",
            ranges.len()
        );
        rows(
            &mut out,
            ranges.iter().map(|(first, last)| format!("(0x{first:05X}, 0x{last:05X}),")),
        );
        out.push_str("];\n");
    }
    Ok(out)
}

/// The text between the braces of the array `name`.
fn array<'a>(text: &'a str, name: &str) -> Result<&'a str, String> {
    let missing = || format!("no array {name}");
    let start = text.find(&format!(" {name}[")).ok_or_else(missing)?;
    let open = start + text[start..].find('{').ok_or_else(missing)?;
    let close = open + text[open..].find("\n};").ok_or_else(missing)?;
    Ok(&text[open + 1..close])
}

/// The entries of a map, one on each line as `value, /* U+code */`, with the code point of the
/// comment. The first entry of a map of case is reserved, with no code point, and gives 0.
fn entries(file: &str, body: &str) -> Result<Vec<(u32, u32)>, String> {
    let mut entries = Vec::new();
    for line in body.lines().map(str::trim).filter(|line| !line.is_empty()) {
        let bad = || format!("{file}: not an entry: {line}");
        let (value, comment) = line.split_once(',').ok_or_else(bad)?;
        let comment = comment.trim().strip_prefix("/*").and_then(|c| c.strip_suffix("*/"));
        let codepoint = match comment.map(str::trim).ok_or_else(bad)? {
            "reserved" => 0,
            comment => {
                let hex = comment.strip_prefix("U+").ok_or_else(bad)?;
                u32::from_str_radix(hex, 16).map_err(|_| bad())?
            }
        };
        entries.push((number(value)?, codepoint));
    }
    Ok(entries)
}

/// An entry of `special_case`: the conditions and up to three code points for each kind.
type Special = (u8, [[u32; 3]; 4]);

/// The entries of `special_case`: the conditions and the code points of each kind of case.
fn specials(body: &str) -> Result<Vec<Special>, String> {
    let mut specials = Vec::new();
    for line in body.lines().map(str::trim).filter(|line| !line.is_empty()) {
        let bad = || format!("unicode_case_table.h: not a special case: {line}");
        let (conditions, rest) =
            line.strip_prefix('{').and_then(|l| l.split_once(',')).ok_or_else(bad)?;
        let conditions = match conditions {
            "0" => 0,
            "PG_U_FINAL_SIGMA" => 1,
            _ => return Err(bad()),
        };
        let mut map = [[0; 3]; 4];
        if specials.is_empty() {
            // The first entry is reserved and has no kinds.
            if conditions != 0 || rest.contains("0x") {
                return Err(bad());
            }
        } else {
            for (at, kind) in KINDS.iter().enumerate() {
                let start = rest.find(&format!("[{kind}] = {{")).ok_or_else(bad)?;
                let inner = &rest[start..];
                let open = inner.find('{').ok_or_else(bad)?;
                let close = inner.find('}').ok_or_else(bad)?;
                let points: Vec<&str> = inner[open + 1..close].split(", ").collect();
                let [a, b, c] = points[..] else { return Err(bad()) };
                map[at] = [number(a)?, number(b)?, number(c)?];
            }
        }
        specials.push((conditions, map));
    }
    Ok(specials)
}

/// The categories of `pg_unicode_category`, in CamelCase, with their values.
fn categories_of(text: &str) -> Result<Vec<(String, u32)>, String> {
    let missing = || "unicode_category.h: no enum pg_unicode_category".to_string();
    let start = text.find("typedef enum pg_unicode_category").ok_or_else(missing)?;
    let open = start + text[start..].find('{').ok_or_else(missing)?;
    let close = open + text[open..].find('}').ok_or_else(missing)?;
    let mut variants = Vec::new();
    for line in text[open + 1..close].lines() {
        let line = line.split("/*").next().unwrap_or_default().trim().trim_end_matches(',');
        if line.is_empty() {
            continue;
        }
        let bad = || format!("unicode_category.h: not a category: {line}");
        let (name, value) = line.split_once(" = ").ok_or_else(bad)?;
        let name = name.strip_prefix("PG_U_").ok_or_else(bad)?;
        let camel: String =
            name.split('_').map(|word| word[..1].to_string() + &word[1..].to_lowercase()).collect();
        variants.push((camel, number(value)?));
    }
    Ok(variants)
}

/// The ranges of `unicode_categories`, as `{first, last, PG_U_NAME}`, with the CamelCase name.
fn category_ranges(
    body: &str,
    variants: &[(String, u32)],
) -> Result<Vec<(u32, u32, String)>, String> {
    let mut ranges = Vec::new();
    for line in body.lines().map(str::trim).filter(|line| !line.is_empty()) {
        let bad = || format!("unicode_category_table.h: not a range: {line}");
        let inner = line.strip_prefix('{').and_then(|l| l.split_once('}')).ok_or_else(bad)?.0;
        let fields: Vec<&str> = inner.split(", ").collect();
        let [first, last, name] = fields[..] else { return Err(bad()) };
        let name = name.strip_prefix("PG_U_").ok_or_else(bad)?.replace('_', "").to_lowercase();
        let (camel, _) =
            variants.iter().find(|(camel, _)| camel.to_lowercase() == name).ok_or_else(bad)?;
        ranges.push((number(first)?, number(last)?, camel.clone()));
    }
    sorted("unicode_categories", ranges.iter().map(|r| (r.0, r.1)))?;
    Ok(ranges)
}

/// The ranges of a property, as `{first, last}`.
fn ranges(body: &str) -> Result<Vec<(u32, u32)>, String> {
    let mut ranges = Vec::new();
    for line in body.lines().map(str::trim).filter(|line| !line.is_empty()) {
        let bad = || format!("unicode_category_table.h: not a range: {line}");
        let inner = line.strip_prefix('{').and_then(|l| l.split_once('}')).ok_or_else(bad)?.0;
        let (first, last) = inner.split_once(", ").ok_or_else(bad)?;
        ranges.push((number(first)?, number(last)?));
    }
    sorted("a property", ranges.iter().copied())?;
    Ok(ranges)
}

/// Checks that the ranges are sorted and do not overlap, which the binary search needs.
fn sorted(name: &str, ranges: impl Iterator<Item = (u32, u32)>) -> Result<(), String> {
    let mut end = None;
    for (first, last) in ranges {
        if first > last || end.is_some_and(|end| first <= end) {
            return Err(format!("unicode_category_table.h: the ranges of {name} are not sorted"));
        }
        end = Some(last);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_entry_takes_the_code_point_of_its_comment() {
        let body = "\n\t0x000000,\t/* reserved */\n\t0x000061,\t\t/* U+000041 */\n";
        assert_eq!(entries("t", body), Ok(vec![(0, 0), (0x61, 0x41)]));
        assert!(entries("t", "\t1,\n").is_err());
    }

    #[test]
    fn a_special_case_has_the_code_points_of_each_kind() {
        let body = "\n\t{0, {{0, 0, 0}, {0, 0, 0}, {0, 0, 0}}},\n\t{PG_U_FINAL_SIGMA, {[CaseLower] = {0x0003c2, 0x000000, 0x000000},[CaseTitle] = {0x0003a3, 0x000000, 0x000000},[CaseUpper] = {0x0003a3, 0x000000, 0x000000},[CaseFold] = {0x0003c3, 0x000000, 0x000000}}},\n";
        let specials = specials(body).unwrap();
        assert_eq!(specials[1], (1, [[0x3C2, 0, 0], [0x3A3, 0, 0], [0x3A3, 0, 0], [0x3C3, 0, 0]]));
    }

    #[test]
    fn the_categories_are_in_camel_case() {
        let text = "typedef enum pg_unicode_category\n{\n\tPG_U_UNASSIGNED = 0,\t/* Cn */\n\tPG_U_DECIMAL_NUMBER = 9 /* Nd */\n} pg_unicode_category;";
        let variants = categories_of(text).unwrap();
        assert_eq!(variants, vec![("Unassigned".to_string(), 0), ("DecimalNumber".to_string(), 9)]);
        let ranges = category_ranges("\n\t{0x000030, 0x000039, PG_U_DECIMAL_NUMBER},\n", &variants);
        assert_eq!(ranges, Ok(vec![(0x30, 0x39, "DecimalNumber".to_string())]));
    }

    #[test]
    fn the_ranges_must_be_sorted() {
        assert!(ranges("\n\t{0x000041, 0x00005a},\n\t{0x000061, 0x00007a},\n").is_ok());
        assert!(ranges("\n\t{0x000061, 0x00007a},\n\t{0x000041, 0x00005a},\n").is_err());
    }
}
