[package]
name = "rudb-duckdb-format"
description = "Reading and writing DuckDB storage format, at every version we claim to support."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
rudb-common.workspace = true
rudb-io.workspace = true
rudb-vector.workspace = true
rudb-encoding.workspace = true

[lints]
workspace = true
