[package]
name = "rudb"
description = "The embedding API: connections, prepared statements, configuration and results."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
rudb-common.workspace = true
rudb-parse.workspace = true
rudb-bind.workspace = true
rudb-opt.workspace = true
rudb-exec.workspace = true
rudb-catalog.workspace = true
rudb-txn.workspace = true
rudb-storage.workspace = true
rudb-vector.workspace = true

[lints]
workspace = true
