[package]
name = "rudb-cli"
description = "The command line shell."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lib]
name = "rudb_cli"
path = "src/lib.rs"

[[bin]]
name = "rudb"
path = "src/main.rs"

[dependencies]
rudb-common.workspace = true
rudb.workspace = true

[lints]
workspace = true
