//! The layer rule.
//!
//! `xtask/layers.toml` gives every crate a rank. A crate may depend only on crates of strictly
//! lower rank. This reads both files and compares them, which is the whole check.
//!
//! The parsing here is line based rather than a TOML library, because the two files it reads are
//! generated by us and stay in the shape it expects. If that ever stops being true, the right fix
//! is a TOML dependency in this crate and not a cleverer parser.

use std::collections::BTreeMap;
use std::path::Path;

pub(crate) fn check(root: &Path) -> Result<(), String> {
    let ranks = read_ranks(root)?;
    let crates_dir = root.join("crates");
    let mut problems = Vec::new();
    let mut checked = 0usize;

    let mut entries: Vec<_> = std::fs::read_dir(&crates_dir)
        .map_err(|e| format!("could not read {}: {e}", crates_dir.display()))?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    entries.sort();

    for dir in entries {
        let name = dir.file_name().and_then(|n| n.to_str()).unwrap_or_default().to_string();
        let Some(&rank) = ranks.get(&name) else {
            problems.push(format!("{name} has no rank in xtask/layers.toml"));
            continue;
        };
        let manifest = dir.join("Cargo.toml");
        let text = std::fs::read_to_string(&manifest)
            .map_err(|e| format!("could not read {}: {e}", manifest.display()))?;
        for dep in dependencies(&text) {
            let Some(&dep_rank) = ranks.get(&dep) else {
                problems.push(format!("{name} depends on {dep}, which has no rank"));
                continue;
            };
            if dep_rank >= rank {
                problems.push(format!(
                    "{name} at rank {rank} depends on {dep} at rank {dep_rank}, which is not strictly lower"
                ));
            }
        }
        checked += 1;
    }

    for name in ranks.keys() {
        if !crates_dir.join(name).is_dir() {
            problems.push(format!("xtask/layers.toml ranks {name}, which is not a crate"));
        }
    }

    if problems.is_empty() {
        println!("the layer rule holds across {checked} crates");
        Ok(())
    } else {
        for problem in &problems {
            eprintln!("  {problem}");
        }
        Err(format!("{} layer violations", problems.len()))
    }
}

pub(crate) fn read_ranks(root: &Path) -> Result<BTreeMap<String, u32>, String> {
    let path = root.join("xtask/layers.toml");
    let text = std::fs::read_to_string(&path)
        .map_err(|e| format!("could not read {}: {e}", path.display()))?;
    let mut ranks = BTreeMap::new();
    let mut inside = false;
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            inside = line == "[ranks]";
            continue;
        }
        if !inside || line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((name, value)) = line.split_once('=') else {
            return Err(format!("layers.toml has a line that is not a rank: {line}"));
        };
        let rank: u32 = value.trim().parse().map_err(|_| {
            format!("layers.toml gives {} a rank that is not a number", name.trim())
        })?;
        ranks.insert(name.trim().to_string(), rank);
    }
    Ok(ranks)
}

/// The workspace crates a manifest depends on. Anything that is not one of ours is not this
/// check's business, so the filter is on the name prefix.
pub(crate) fn dependencies(manifest: &str) -> Vec<String> {
    let mut deps = Vec::new();
    let mut inside = false;
    for line in manifest.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            inside = line.ends_with("dependencies]");
            continue;
        }
        if !inside || line.is_empty() || line.starts_with('#') {
            continue;
        }
        let name = line.split(['=', '.']).next().unwrap_or_default().trim();
        if name == "rudb" || name.starts_with("rudb-") {
            deps.push(name.to_string());
        }
    }
    deps
}
