[package]
name = "rudb-csv"
description = "The CSV reader and writer, including dialect sniffing and type inference."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
rudb-common.workspace = true
rudb-io.workspace = true
rudb-kernels.workspace = true
rudb-vector.workspace = true

[lints]
workspace = true
